# Generated by Django 5.1.4 on 2025-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('media', models.FileField(blank=True, null=True, upload_to='banners/')),
                ('start_time', models.DateTimeField(blank=True, help_text='Optional: start time for scheduled banner display', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Optional: end time for scheduled banner display', null=True)),
                ('active', models.BooleanField(default=True, help_text='Enable/disable banner')),
            ],
        ),
    ]
